Block diagrams
upb-lea/gem-control pull request #14
Opened 2022-05-09 13:44 UTC by fbook98

2022-05-22 13:26 UTC, atra94 requested changes, later dismissed
I know that this repository lacks a lot of documentation in general. However, new code should be commented.

Except for a few files there is not a single comment.

2022-05-22 13:26 UTC, atra94 commented on gem_controllers/block_diagrams/stage_blocks/ext_ex_dc_cc.py
> +def ext_ex_dc_cc(emf_feedforward):
Please document this function

2022-09-05 11:16 UTC, max-schenke commented
The pi_current_controller and torque_controller seem to be missing within the state blocks.
Therefore, the imports fail when I launch the example.py.

2022-09-20 06:05 UTC, max-schenke commented on example.py
> +if __name__ == '__main__':
"env_id" got deleted and I think everything after the if clause should also be indented.

2022-10-11 07:52 UTC, max-schenke approved these changes
Looks good, code could use some more documentation but this can be added later.
Thanks!

2022-10-14 06:52 UTC, merged