Eesm controller
upb-lea/gem-control pull request #15
Opened 2022-07-28 08:53 UTC by fbook98

2022-09-06 06:43 UTC, max-schenke commented
![grafik](https://user-images.githubusercontent.com/61693487/188564528-4b5f5ed4-c3f9-485d-941a-21019e38aa4c.png)

The import of the state_action_processors seems not to work with the latest version of GEM. 
It should be physical_system_wrappers I think.

2022-09-20 06:10 UTC, max-schenke commented on example.py
> -    )
The example has now been fitted to only work with the SCIM. Either name it that way and also provide an example for another motor or catch it via some case distinction such that one example file can be used for all motor classes.

2022-11-08 15:15 UTC, bhk11 requested changes
There is a problem with the generation of the block diagramm for the ExtExDC Motor, when TC or SC is chosen. When I turnoff the block digramm it works fine. Then I also mentiond that the 3 phase drives doesn't work with finite action sets, is that correct?

2022-11-08 15:15 UTC, bhk11 commented on example.py
> +    motor_type = 'EESM'     # 'PermExDc', 'ExtExDc', 'SeriesDc', 'ShuntDc', 'PMSM', 'EESM', 'SynRM' or 'SCIM'
Cont + TC + ExtExDc rises a latex error while writing the block diagram, but the result in the pdf looks fine.
![image](https://user-images.githubusercontent.com/95769661/200592074-ee003e1f-66b9-4f8a-b65b-de1cf6d1cd6a.png)
{
	"name": "CalledProcessError",
	"message": "Command '['pdflatex', '--interaction=nonstopmode', 'c:\\\\Repositories\\\\Python\\\\GEM-control\\\\ControlBlockDiagram.tex']' returned non-zero exit status 1.",
	"stack": "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[1;31mCalledProcessError\u001b[0m                        Traceback (most recent call last)\n\u001b[1;32mc:\\Repositories\\Python\\GEM-control\\example.ipynb Cell 1\u001b[0m in \u001b[0;36m<cell line: 35>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=24'>25</a>\u001b[0m c \u001b[39m=\u001b[39m gc\u001b[39m.\u001b[39mGemController\u001b[39m.\u001b[39mmake(\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=25'>26</a>\u001b[0m         env,\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=26'>27</a>\u001b[0m         env_id,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=30'>31</a>\u001b[0m         save_block_diagram_as\u001b[39m=\u001b[39m(),\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=31'>32</a>\u001b[0m )\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=33'>34</a>\u001b[0m \u001b[39m# Control the environment\u001b[39;00m\n\u001b[1;32m---> <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=34'>35</a>\u001b[0m c\u001b[39m.\u001b[39;49mcontrol_environment(env, n_steps\u001b[39m=\u001b[39;49m\u001b[39m30000\u001b[39;49m, render_env\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m, max_episode_length\u001b[39m=\u001b[39;49m\u001b[39m10000\u001b[39;49m)\n\nFile \u001b[1;32mc:\\Repositories\\Python\\GEM-control\\gem_controllers\\gem_controller.py:110\u001b[0m, in \u001b[0;36mGemController.control_environment\u001b[1;34m(self, env, n_steps, max_episode_length, render_env)\u001b[0m\n\u001b[0;32m    108\u001b[0m state, reference \u001b[39m=\u001b[39m env\u001b[39m.\u001b[39mreset()\n\u001b[0;32m    109\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mblock_diagram:\n\u001b[1;32m--> 110\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mblock_diagram\u001b[39m.\u001b[39;49mopen()\n\u001b[0;32m    111\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mreset()\n\u001b[0;32m    112\u001b[0m current_episode_length \u001b[39m=\u001b[39m \u001b[39m0\u001b[39m\n\nFile \u001b[1;32mc:\\Users\\bhk\\Anaconda3\\envs\\test_CTRL\\lib\\site-packages\\control_block_diagram\\control_diagram.py:189\u001b[0m, in \u001b[0;36mControllerDiagram.open\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    182\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    183\u001b[0m \u001b[39m    Opens an existing PDF file in the PDF Viewer or creates a temporary PDF file. The PDF Viewer is started in\u001b[39;00m\n\u001b[0;32m    184\u001b[0m \u001b[39m    the background so that the program flow is not interrupted. The window is closed by the close method and\u001b[39;00m\n\u001b[0;32m    185\u001b[0m \u001b[39m    the temporary PDF file is deleted.\u001b[39;00m\n\u001b[0;32m    186\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    188\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39m'\u001b[39m\u001b[39mipykernel\u001b[39m\u001b[39m'\u001b[39m \u001b[39min\u001b[39;00m sys\u001b[39m.\u001b[39mmodules:\n\u001b[1;32m--> 189\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_build_local()\n\u001b[0;32m    190\u001b[0m     display(PDFViewerNB(\u001b[39m'\u001b[39m\u001b[39mControlBlockDiagram.pdf\u001b[39m\u001b[39m'\u001b[39m, size\u001b[39m=\u001b[39m(\u001b[39mint\u001b[39m(\u001b[39mmin\u001b[39m(\u001b[39m900\u001b[39m, \u001b[39mself\u001b[39m\u001b[39m.\u001b[39msize[\u001b[39m0\u001b[39m] \u001b[39m*\u001b[39m \u001b[39m50\u001b[39m \u001b[39m+\u001b[39m \u001b[39m50\u001b[39m)),\n\u001b[0;32m    191\u001b[0m                                                         \u001b[39mint\u001b[39m(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39msize[\u001b[39m1\u001b[39m] \u001b[39m*\u001b[39m \u001b[39m50\u001b[39m \u001b[39m+\u001b[39m \u001b[39m50\u001b[39m))))\n\u001b[0;32m    192\u001b[0m \u001b[39melse\u001b[39;00m:\n\nFile \u001b[1;32mc:\\Users\\bhk\\Anaconda3\\envs\\test_CTRL\\lib\\site-packages\\control_block_diagram\\control_diagram.py:173\u001b[0m, in \u001b[0;36mControllerDiagram._build_local\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    171\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_doc \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_changed:\n\u001b[0;32m    172\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_build()\n\u001b[1;32m--> 173\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_doc\u001b[39m.\u001b[39;49mgenerate_pdf(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_local_name, compiler\u001b[39m=\u001b[39;49m\u001b[39m'\u001b[39;49m\u001b[39mpdflatex\u001b[39;49m\u001b[39m'\u001b[39;49m, clean_tex\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m)\n\nFile \u001b[1;32mc:\\Users\\bhk\\Anaconda3\\envs\\test_CTRL\\lib\\site-packages\\pylatex\\document.py:250\u001b[0m, in \u001b[0;36mDocument.generate_pdf\u001b[1;34m(self, filepath, clean, clean_tex, compiler, compiler_args, silent)\u001b[0m\n\u001b[0;32m    247\u001b[0m command \u001b[39m=\u001b[39m [compiler] \u001b[39m+\u001b[39m arguments \u001b[39m+\u001b[39m compiler_args \u001b[39m+\u001b[39m main_arguments\n\u001b[0;32m    249\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 250\u001b[0m     output \u001b[39m=\u001b[39m subprocess\u001b[39m.\u001b[39mcheck_output(command,\n\u001b[0;32m    251\u001b[0m                                      stderr\u001b[39m=\u001b[39msubprocess\u001b[39m.\u001b[39mSTDOUT,\n\u001b[0;32m    252\u001b[0m                                      \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcheck_output_kwargs)\n\u001b[0;32m    253\u001b[0m \u001b[39mexcept\u001b[39;00m (\u001b[39mOSError\u001b[39;00m, \u001b[39mIOError\u001b[39;00m) \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m    254\u001b[0m     \u001b[39m# Use FileNotFoundError when python 2 is dropped\u001b[39;00m\n\u001b[0;32m    255\u001b[0m     os_error \u001b[39m=\u001b[39m e\n\nFile \u001b[1;32mc:\\Users\\bhk\\Anaconda3\\envs\\test_CTRL\\lib\\subprocess.py:424\u001b[0m, in \u001b[0;36mcheck_output\u001b[1;34m(timeout, *popenargs, **kwargs)\u001b[0m\n\u001b[0;32m    421\u001b[0m         empty \u001b[39m=\u001b[39m \u001b[39mb\u001b[39m\u001b[39m'\u001b[39m\u001b[39m'\u001b[39m\n\u001b[0;32m    422\u001b[0m     kwargs[\u001b[39m'\u001b[39m\u001b[39minput\u001b[39m\u001b[39m'\u001b[39m] \u001b[39m=\u001b[39m empty\n\u001b[1;32m--> 424\u001b[0m \u001b[39mreturn\u001b[39;00m run(\u001b[39m*\u001b[39mpopenargs, stdout\u001b[39m=\u001b[39mPIPE, timeout\u001b[39m=\u001b[39mtimeout, check\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m,\n\u001b[0;32m    425\u001b[0m            \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\u001b[39m.\u001b[39mstdout\n\nFile \u001b[1;32mc:\\Users\\bhk\\Anaconda3\\envs\\test_CTRL\\lib\\subprocess.py:528\u001b[0m, in \u001b[0;36mrun\u001b[1;34m(input, capture_output, timeout, check, *popenargs, **kwargs)\u001b[0m\n\u001b[0;32m    526\u001b[0m     retcode \u001b[39m=\u001b[39m process\u001b[39m.\u001b[39mpoll()\n\u001b[0;32m    527\u001b[0m     \u001b[ [...]

2022-11-08 15:15 UTC, bhk11 commented on example.py
> +    motor_type = 'EESM'     # 'PermExDc', 'ExtExDc', 'SeriesDc', 'ShuntDc', 'PMSM', 'EESM', 'SynRM' or 'SCIM'
Also for Finite

2022-11-08 15:15 UTC, bhk11 commented on example.py
> +    motor_type = 'EESM'     # 'PermExDc', 'ExtExDc', 'SeriesDc', 'ShuntDc', 'PMSM', 'EESM', 'SynRM' or 'SCIM'
Also for both control sets in Speed control. With blockdiagram = False it works fine.

2022-11-08 15:15 UTC, bhk11 commented on example.py
> +    motor_type = 'EESM'     # 'PermExDc', 'ExtExDc', 'SeriesDc', 'ShuntDc', 'PMSM', 'EESM', 'SynRM' or 'SCIM'
Not implemented error for Finite + SC + PMSM
![image](https://user-images.githubusercontent.com/95769661/200595890-518983d3-7f73-45c2-997a-3e9c3515efb3.png)

2022-11-08 15:15 UTC, bhk11 commented on example.py
> +    motor_type = 'EESM'     # 'PermExDc', 'ExtExDc', 'SeriesDc', 'ShuntDc', 'PMSM', 'EESM', 'SynRM' or 'SCIM'
{
	"name": "NotImplementedError",
	"message": "",
	"stack": "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[1;31mNotImplementedError\u001b[0m                       Traceback (most recent call last)\n\u001b[1;32mc:\\Repositories\\Python\\GEM-control\\example.ipynb Cell 1\u001b[0m in \u001b[0;36m<cell line: 35>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=24'>25</a>\u001b[0m c \u001b[39m=\u001b[39m gc\u001b[39m.\u001b[39mGemController\u001b[39m.\u001b[39mmake(\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=25'>26</a>\u001b[0m         env,\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=26'>27</a>\u001b[0m         env_id,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=30'>31</a>\u001b[0m         save_block_diagram_as\u001b[39m=\u001b[39m(),\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=31'>32</a>\u001b[0m )\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=33'>34</a>\u001b[0m \u001b[39m# Control the environment\u001b[39;00m\n\u001b[1;32m---> <a href='vscode-notebook-cell:/c%3A/Repositories/Python/GEM-control/example.ipynb#W0sZmlsZQ%3D%3D?line=34'>35</a>\u001b[0m c\u001b[39m.\u001b[39;49mcontrol_environment(env, n_steps\u001b[39m=\u001b[39;49m\u001b[39m30000\u001b[39;49m, render_env\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m, max_episode_length\u001b[39m=\u001b[39;49m\u001b[39m10000\u001b[39;49m)\n\nFile \u001b[1;32mc:\\Repositories\\Python\\GEM-control\\gem_controllers\\gem_controller.py:116\u001b[0m, in \u001b[0;36mGemController.control_environment\u001b[1;34m(self, env, n_steps, max_episode_length, render_env)\u001b[0m\n\u001b[0;32m    114\u001b[0m \u001b[39mif\u001b[39;00m render_env:\n\u001b[0;32m    115\u001b[0m     env\u001b[39m.\u001b[39mrender()\n\u001b[1;32m--> 116\u001b[0m action \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mcontrol(state, reference)\n\u001b[0;32m    117\u001b[0m (state, reference), _, done, _ \u001b[39m=\u001b[39m env\u001b[39m.\u001b[39mstep(action)\n\u001b[0;32m    118\u001b[0m \u001b[39mif\u001b[39;00m done \u001b[39mor\u001b[39;00m current_episode_length \u001b[39m>\u001b[39m\u001b[39m=\u001b[39m max_episode_length:\n\nFile \u001b[1;32mc:\\Repositories\\Python\\GEM-control\\gem_controllers\\gem_adapter.py:63\u001b[0m, in \u001b[0;36mGymElectricMotorAdapter.control\u001b[1;34m(self, state, reference)\u001b[0m\n\u001b[0;32m     61\u001b[0m denormalized_ref \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_input_stage(state_, reference_)\n\u001b[0;32m     62\u001b[0m voltage_set_point \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_controller\u001b[39m.\u001b[39mcontrol(state_, denormalized_ref)\n\u001b[1;32m---> 63\u001b[0m action \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_output_stage(state_, voltage_set_point)\n\u001b[0;32m     64\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_reference_plotter\u001b[39m.\u001b[39mupdate_plots(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_controller\u001b[39m.\u001b[39mreferences)\n\u001b[0;32m     65\u001b[0m \u001b[39mreturn\u001b[39;00m action\n\nFile \u001b[1;32mc:\\Repositories\\Python\\GEM-control\\gem_controllers\\stages\\disc_output_stage.py:32\u001b[0m, in \u001b[0;36mDiscOutputStage.__call__\u001b[1;34m(self, state, reference)\u001b[0m\n\u001b[0;32m     31\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m__call__\u001b[39m(\u001b[39mself\u001b[39m, state, reference):\n\u001b[1;32m---> 32\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_output_stage(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mto_action(state, reference))\n\nFile \u001b[1;32mc:\\Repositories\\Python\\GEM-control\\gem_controllers\\stages\\disc_output_stage.py:40\u001b[0m, in \u001b[0;36mDiscOutputStage.to_b6_discrete\u001b[1;34m(multi_discrete_action)\u001b[0m\n\u001b[0;32m     38\u001b[0m \u001b[39m@staticmethod\u001b[39m\n\u001b[0;32m     39\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mto_b6_discrete\u001b[39m(multi_discrete_action):\n\u001b[1;32m---> 40\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mNotImplementedError\u001b[39;00m\n\n\u001b[1;31mNotImplementedError\u001b[0m: "
}

2022-11-08 15:15 UTC, bhk11 commented on example.py
> +    motor_type = 'EESM'     # 'PermExDc', 'ExtExDc', 'SeriesDc', 'ShuntDc', 'PMSM', 'EESM', 'SynRM' or 'SCIM'
Also for Finite + TC + PMSM

2022-11-08 15:15 UTC, bhk11 commented on example.py
> +    motor_type = 'EESM'     # 'PermExDc', 'ExtExDc', 'SeriesDc', 'ShuntDc', 'PMSM', 'EESM', 'SynRM' or 'SCIM'
Also for Finite + CC + PMSM

2022-11-08 15:15 UTC, bhk11 commented on example.py
> +    motor_type = 'EESM'     # 'PermExDc', 'ExtExDc', 'SeriesDc', 'ShuntDc', 'PMSM', 'EESM', 'SynRM' or 'SCIM'
Also for all finite EESM Controls rises the not implemented error.

2022-11-08 15:15 UTC, bhk11 commented on example.py
> +    motor_type = 'EESM'     # 'PermExDc', 'ExtExDc', 'SeriesDc', 'ShuntDc', 'PMSM', 'EESM', 'SynRM' or 'SCIM'
Same for all Finite SynRM and SCIM.

2022-11-08 16:41 UTC, bhk11 approved these changes
ExtExDc block diagramm works now as expected.

2022-11-09 17:14 UTC, bhk11 approved these changes
Looks good now, but we should keep in mind to take a deeper look into the finite action space. Some of the controller reset often. My guess is that it's an issue with the default step size, which work fine for continuous but has to be smaller for finite sets.

2022-11-22 10:39 UTC, fbook98 commented
> Looks good now, but we should keep in mind to take a deeper look into the finite action space. Some of the controller reset often. My guess is that it's an issue with the default step size, which work fine for continuous but has to be smaller for finite sets.

The problem with the SCIM can be solved by reducing the step size. For the EESM there were two small bugs that are now fixed.

2023-03-03 14:37 UTC, closed without merging