Sphinx doc
upb-lea/gem-control pull request #19
Opened 2022-10-26 07:32 UTC by fbook98

2022-10-26 13:05 UTC, bhk11 requested changes
The Sphinx doc looks good. I found some minor optical bugs. In general there are some changes in the writing of X controller with and without dash. Also somtimes controller with capital C. I would write it without the dash and exept of headlines the control/controller with small c.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/_sources/parts/usage_guide/usage_guides.rst.txt
> +the environment. In the following code block an example for the initialization of a speed control of an PMSM is
I guess there has to be a comma after "in the following code block"

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/_modules/gem_controllers/stages/stage.html
> +    <span class="sd">&quot;&quot;&quot;The stage is the basic entity in the gem-controller structure. &quot;&quot;&quot;</span>
I would personaly prefer element or module instead of entity in the sentence.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/_modules/gem_controllers/stages/base_controllers/base_controller.html
> +<span class="sd">        Args:</span>
The args of the function are not correct displayed in the docs.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/base_controllers/i_controller.html
> +:param state: The state of the environment.
List of args not correct displayed in the docs.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/operation_point_selection/permex_dc_ops.html
> +:param state: The state of the environment.
The list of args is not fully displayed as list.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/operation_point_selection/extex_dc_ops.html
> +:param state: The state of the environment.
The list of args is not fully displayed as list.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/operation_point_selection/series_dc_ops.html
> +:param state: The state of the environment.
The list of args is not fully displayed as list.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/operation_point_selection/shunt_dc_ops.html
> +:param state: The state of the environment.
The list of args is not fully displayed as list.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/operation_point_selection/foc_ops.html
> +:param state: The state of the environment.
The list of args is not fully displayed as list.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/operation_point_selection/pmsm_ops.html
> +<dd><p>Get the i_d and i_q current from the mtpc lut</p>
I would prefer capital letters for MTPC and MPTF.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/operation_point_selection/eesm_ops.html
> +:param psi: optimal magnetic flux.
List is not fully displayed as a list.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/operation_point_selection/eesm_ops.html
> +:param torque: The clipped torque reference value.
List is not fully displayed as a list.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/abc_transformation.html
> +<dd><p>This class calculates the transformation from the dq-coordinate system to the abc-coordinatesystem for three-
In the docs is a blank displayed in three- phase.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/input_stage.html
> +:param state: The state of the environment.
List is not fully displayed as a list.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/cont_output_stage.html
> +:param env: The GEM-Environment that the controller shall be created for.
The list of parameters is not displayed correct in the docs.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/stages/disc_output_stage.html
> +:param multi_discrete_action: Array of multi discrete actions
List is not fully displayed as a list.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/block_diagrams/block_diagrams.html
> +<p>Returns:    Control Block Diagram</p>
Returns are not correct displayed in the docs.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/block_diagrams/block_diagrams.html
> +<p>Returns:        list of all block building functions</p>
Returns are not correct displayed in the docs.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/reference_plotter.html
> +:param env: The GEM-Environment that the controller shall be created for.
No list is displayed.

2022-10-26 13:05 UTC, bhk11 commented on docs/_build/html/parts/api_documentation/reference_plotter.html
> +<dd><p>Update the state plots of the GEM environment
No list is displayed.

2022-10-26 13:05 UTC, bhk11 commented on docs/_modules/gem_controllers/utils.html
> +
Forward to the last page GEM Controllers is not shown.

2022-11-08 12:12 UTC, bhk11 reviewed
Documentation looks good. I found some minor issues, when I looked into.

As mentioned before, it is not possible to use the next button in the bottom of the "Utils" page to go into the next chapter "GEM Controllers" of the side tree.

2022-11-08 12:12 UTC, bhk11 commented on gem_controllers/stages/base_controllers/pi_controller.py
> +        Tune the P-controller and I-controller for the flux control by the symmetrical optimum.
Here, P and I controller is written with a hyphen. The discription of the other function has not the hyphen in P and I controller.

2022-11-08 12:12 UTC, bhk11 commented on gem_controllers/stages/base_controllers/pid_controller.py
> +        """Set the gains of the P-, I- and D-Component for the current control.
On previous page (PI controller), component has a small starting letter.

2022-11-08 12:12 UTC, bhk11 commented on gem_controllers/stages/base_controllers/pid_controller.py
> +        """Set the gains of the P-, I- and D-Component for the speed control.
On previous page (PI controller), component has a small starting letter.

2022-11-08 12:12 UTC, bhk11 commented on gem_controllers/stages/abc_transformation.py
> +    """This class calculates the transformation from the dq-coordinate system to the abc-coordinatesystem for three-
Between three- and phases is a blank.

2022-11-08 13:30 UTC, fbook98 commented
> As mentioned before, it is not possible to use the next button in the bottom of the "Utils" page to go into the next chapter "GEM Controllers" of the side tree.

"GEM Controllers" is not a standalone page, but only a section on the "GEM Control API Documentation" page. There is no "Next" button on the "Utils" page, since this is the last standalone page.

2022-11-08 16:41 UTC, bhk11 commented on docs/_build/html/_modules/gem_controllers/stages/base_controllers/pid_controller.html
> +        <span class="sd">&quot;&quot;&quot;Set the gains of the P, I and D component for the current control.</span>
Now, it's here without hypen between P I D and component. Before it was always with (compare page for PI controller or other function on this page.)

2022-11-08 16:41 UTC, bhk11 commented on docs/_build/html/_modules/gem_controllers/stages/base_controllers/pid_controller.html
> +        <span class="sd">&quot;&quot;&quot;Set the gains of the P-, I- and D-Component for the speed control.</span>
Here is componont as it was with a capital letter.

2023-03-03 13:09 UTC, merged